// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: rate_limiter.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_rate_limiter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{0}
}

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WindowSeconds uint32                 `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Cost          uint32                 `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,6,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_rate_limiter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{1}
}

func (x *CheckRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *CheckRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *CheckRequest) GetWindowSeconds() uint32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *CheckRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *CheckRequest) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *CheckRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     uint32                 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	Limit         uint32                 `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	RetryAfterMs  int64                  `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	ResetAt       int64                  `protobuf:"varint,5,opt,name=reset_at,json=resetAt,proto3" json:"reset_at,omitempty"`
	Algorithm     string                 `protobuf:"bytes,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_rate_limiter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{2}
}

func (x *CheckResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckResponse) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *CheckResponse) GetLimit() uint32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CheckResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *CheckResponse) GetResetAt() int64 {
	if x != nil {
		return x.ResetAt
	}
	return 0
}

func (x *CheckResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

type VisualizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Algorithm     string                 `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,3,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WindowSeconds uint32                 `protobuf:"varint,4,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizeRequest) Reset() {
	*x = VisualizeRequest{}
	mi := &file_rate_limiter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizeRequest) ProtoMessage() {}

func (x *VisualizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizeRequest.ProtoReflect.Descriptor instead.
func (*VisualizeRequest) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{3}
}

func (x *VisualizeRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VisualizeRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *VisualizeRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *VisualizeRequest) GetWindowSeconds() uint32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type VisualizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	State         map[string]string      `protobuf:"bytes,3,rep,name=state,proto3" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // simplified, real would use struct
	Diagram       string                 `protobuf:"bytes,4,opt,name=diagram,proto3" json:"diagram,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisualizeResponse) Reset() {
	*x = VisualizeResponse{}
	mi := &file_rate_limiter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisualizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisualizeResponse) ProtoMessage() {}

func (x *VisualizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisualizeResponse.ProtoReflect.Descriptor instead.
func (*VisualizeResponse) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{4}
}

func (x *VisualizeResponse) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *VisualizeResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VisualizeResponse) GetState() map[string]string {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *VisualizeResponse) GetDiagram() string {
	if x != nil {
		return x.Diagram
	}
	return ""
}

type SimulateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WindowSeconds uint32                 `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	Algorithm     string                 `protobuf:"bytes,4,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Costs         []uint32               `protobuf:"varint,5,rep,packed,name=costs,proto3" json:"costs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateRequest) Reset() {
	*x = SimulateRequest{}
	mi := &file_rate_limiter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRequest) ProtoMessage() {}

func (x *SimulateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRequest.ProtoReflect.Descriptor instead.
func (*SimulateRequest) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{5}
}

func (x *SimulateRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SimulateRequest) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *SimulateRequest) GetWindowSeconds() uint32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

func (x *SimulateRequest) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *SimulateRequest) GetCosts() []uint32 {
	if x != nil {
		return x.Costs
	}
	return nil
}

type SimulateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SimulateResult      `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateResponse) Reset() {
	*x = SimulateResponse{}
	mi := &file_rate_limiter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateResponse) ProtoMessage() {}

func (x *SimulateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateResponse.ProtoReflect.Descriptor instead.
func (*SimulateResponse) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{6}
}

func (x *SimulateResponse) GetResults() []*SimulateResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SimulateResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cost          uint32                 `protobuf:"varint,1,opt,name=cost,proto3" json:"cost,omitempty"`
	Allowed       bool                   `protobuf:"varint,2,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Remaining     uint32                 `protobuf:"varint,3,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateResult) Reset() {
	*x = SimulateResult{}
	mi := &file_rate_limiter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateResult) ProtoMessage() {}

func (x *SimulateResult) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateResult.ProtoReflect.Descriptor instead.
func (*SimulateResult) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{7}
}

func (x *SimulateResult) GetCost() uint32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *SimulateResult) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *SimulateResult) GetRemaining() uint32 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Pattern       string                 `protobuf:"bytes,2,opt,name=pattern,proto3" json:"pattern,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,3,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Config        *LimitConfig           `protobuf:"bytes,4,opt,name=config,proto3" json:"config,omitempty"`
	Priority      int32                  `protobuf:"varint,5,opt,name=priority,proto3" json:"priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_rate_limiter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{8}
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetPattern() string {
	if x != nil {
		return x.Pattern
	}
	return ""
}

func (x *Policy) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *Policy) GetConfig() *LimitConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Policy) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

type LimitConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     string                 `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	MaxTokens     uint32                 `protobuf:"varint,2,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	WindowSeconds uint32                 `protobuf:"varint,3,opt,name=window_seconds,json=windowSeconds,proto3" json:"window_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LimitConfig) Reset() {
	*x = LimitConfig{}
	mi := &file_rate_limiter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LimitConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LimitConfig) ProtoMessage() {}

func (x *LimitConfig) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LimitConfig.ProtoReflect.Descriptor instead.
func (*LimitConfig) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{9}
}

func (x *LimitConfig) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *LimitConfig) GetMaxTokens() uint32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *LimitConfig) GetWindowSeconds() uint32 {
	if x != nil {
		return x.WindowSeconds
	}
	return 0
}

type PoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*Policy              `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoliciesResponse) Reset() {
	*x = PoliciesResponse{}
	mi := &file_rate_limiter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoliciesResponse) ProtoMessage() {}

func (x *PoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoliciesResponse.ProtoReflect.Descriptor instead.
func (*PoliciesResponse) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{10}
}

func (x *PoliciesResponse) GetPolicies() []*Policy {
	if x != nil {
		return x.Policies
	}
	return nil
}

type PolicyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyResponse) Reset() {
	*x = PolicyResponse{}
	mi := &file_rate_limiter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyResponse) ProtoMessage() {}

func (x *PolicyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyResponse.ProtoReflect.Descriptor instead.
func (*PolicyResponse) Descriptor() ([]byte, []int) {
	return file_rate_limiter_proto_rawDescGZIP(), []int{11}
}

func (x *PolicyResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PolicyResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_rate_limiter_proto protoreflect.FileDescriptor

const file_rate_limiter_proto_rawDesc = "" +
	"\n" +
	"\x12rate_limiter.proto\x12\vratelimiter\"\a\n" +
	"\x05Empty\"\x92\x02\n" +
	"\fCheckRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\rR\tmaxTokens\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\rR\rwindowSeconds\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\rR\x04cost\x12=\n" +
	"\x06labels\x18\x06 \x03(\v2%.ratelimiter.CheckRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbc\x01\n" +
	"\rCheckResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\rR\tremaining\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\rR\x05limit\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x03R\fretryAfterMs\x12\x19\n" +
	"\breset_at\x18\x05 \x01(\x03R\aresetAt\x12\x1c\n" +
	"\talgorithm\x18\x06 \x01(\tR\talgorithm\"\x88\x01\n" +
	"\x10VisualizeRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1c\n" +
	"\talgorithm\x18\x02 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x03 \x01(\rR\tmaxTokens\x12%\n" +
	"\x0ewindow_seconds\x18\x04 \x01(\rR\rwindowSeconds\"\xd8\x01\n" +
	"\x11VisualizeResponse\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12?\n" +
	"\x05state\x18\x03 \x03(\v2).ratelimiter.VisualizeResponse.StateEntryR\x05state\x12\x18\n" +
	"\adiagram\x18\x04 \x01(\tR\adiagram\x1a8\n" +
	"\n" +
	"StateEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x9d\x01\n" +
	"\x0fSimulateRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\rR\tmaxTokens\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\rR\rwindowSeconds\x12\x1c\n" +
	"\talgorithm\x18\x04 \x01(\tR\talgorithm\x12\x14\n" +
	"\x05costs\x18\x05 \x03(\rR\x05costs\"I\n" +
	"\x10SimulateResponse\x125\n" +
	"\aresults\x18\x01 \x03(\v2\x1b.ratelimiter.SimulateResultR\aresults\"\\\n" +
	"\x0eSimulateResult\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\rR\x04cost\x12\x18\n" +
	"\aallowed\x18\x02 \x01(\bR\aallowed\x12\x1c\n" +
	"\tremaining\x18\x03 \x01(\rR\tremaining\"\xf8\x01\n" +
	"\x06Policy\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\apattern\x18\x02 \x01(\tR\apattern\x127\n" +
	"\x06labels\x18\x03 \x03(\v2\x1f.ratelimiter.Policy.LabelsEntryR\x06labels\x120\n" +
	"\x06config\x18\x04 \x01(\v2\x18.ratelimiter.LimitConfigR\x06config\x12\x1a\n" +
	"\bpriority\x18\x05 \x01(\x05R\bpriority\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"q\n" +
	"\vLimitConfig\x12\x1c\n" +
	"\talgorithm\x18\x01 \x01(\tR\talgorithm\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x02 \x01(\rR\tmaxTokens\x12%\n" +
	"\x0ewindow_seconds\x18\x03 \x01(\rR\rwindowSeconds\"C\n" +
	"\x10PoliciesResponse\x12/\n" +
	"\bpolicies\x18\x01 \x03(\v2\x13.ratelimiter.PolicyR\bpolicies\"<\n" +
	"\x0ePolicyResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name2\xe3\x02\n" +
	"\vRateLimiter\x12>\n" +
	"\x05Check\x12\x19.ratelimiter.CheckRequest\x1a\x1a.ratelimiter.CheckResponse\x12J\n" +
	"\tVisualize\x12\x1d.ratelimiter.VisualizeRequest\x1a\x1e.ratelimiter.VisualizeResponse\x12G\n" +
	"\bSimulate\x12\x1c.ratelimiter.SimulateRequest\x1a\x1d.ratelimiter.SimulateResponse\x12@\n" +
	"\vGetPolicies\x12\x12.ratelimiter.Empty\x1a\x1d.ratelimiter.PoliciesResponse\x12=\n" +
	"\tAddPolicy\x12\x13.ratelimiter.Policy\x1a\x1b.ratelimiter.PolicyResponseB3Z1github.com/crypto/rate-limiter-service/limiter/pbb\x06proto3"

var (
	file_rate_limiter_proto_rawDescOnce sync.Once
	file_rate_limiter_proto_rawDescData []byte
)

func file_rate_limiter_proto_rawDescGZIP() []byte {
	file_rate_limiter_proto_rawDescOnce.Do(func() {
		file_rate_limiter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rate_limiter_proto_rawDesc), len(file_rate_limiter_proto_rawDesc)))
	})
	return file_rate_limiter_proto_rawDescData
}

var file_rate_limiter_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_rate_limiter_proto_goTypes = []any{
	(*Empty)(nil),             // 0: ratelimiter.Empty
	(*CheckRequest)(nil),      // 1: ratelimiter.CheckRequest
	(*CheckResponse)(nil),     // 2: ratelimiter.CheckResponse
	(*VisualizeRequest)(nil),  // 3: ratelimiter.VisualizeRequest
	(*VisualizeResponse)(nil), // 4: ratelimiter.VisualizeResponse
	(*SimulateRequest)(nil),   // 5: ratelimiter.SimulateRequest
	(*SimulateResponse)(nil),  // 6: ratelimiter.SimulateResponse
	(*SimulateResult)(nil),    // 7: ratelimiter.SimulateResult
	(*Policy)(nil),            // 8: ratelimiter.Policy
	(*LimitConfig)(nil),       // 9: ratelimiter.LimitConfig
	(*PoliciesResponse)(nil),  // 10: ratelimiter.PoliciesResponse
	(*PolicyResponse)(nil),    // 11: ratelimiter.PolicyResponse
	nil,                       // 12: ratelimiter.CheckRequest.LabelsEntry
	nil,                       // 13: ratelimiter.VisualizeResponse.StateEntry
	nil,                       // 14: ratelimiter.Policy.LabelsEntry
}
var file_rate_limiter_proto_depIdxs = []int32{
	12, // 0: ratelimiter.CheckRequest.labels:type_name -> ratelimiter.CheckRequest.LabelsEntry
	13, // 1: ratelimiter.VisualizeResponse.state:type_name -> ratelimiter.VisualizeResponse.StateEntry
	7,  // 2: ratelimiter.SimulateResponse.results:type_name -> ratelimiter.SimulateResult
	14, // 3: ratelimiter.Policy.labels:type_name -> ratelimiter.Policy.LabelsEntry
	9,  // 4: ratelimiter.Policy.config:type_name -> ratelimiter.LimitConfig
	8,  // 5: ratelimiter.PoliciesResponse.policies:type_name -> ratelimiter.Policy
	1,  // 6: ratelimiter.RateLimiter.Check:input_type -> ratelimiter.CheckRequest
	3,  // 7: ratelimiter.RateLimiter.Visualize:input_type -> ratelimiter.VisualizeRequest
	5,  // 8: ratelimiter.RateLimiter.Simulate:input_type -> ratelimiter.SimulateRequest
	0,  // 9: ratelimiter.RateLimiter.GetPolicies:input_type -> ratelimiter.Empty
	8,  // 10: ratelimiter.RateLimiter.AddPolicy:input_type -> ratelimiter.Policy
	2,  // 11: ratelimiter.RateLimiter.Check:output_type -> ratelimiter.CheckResponse
	4,  // 12: ratelimiter.RateLimiter.Visualize:output_type -> ratelimiter.VisualizeResponse
	6,  // 13: ratelimiter.RateLimiter.Simulate:output_type -> ratelimiter.SimulateResponse
	10, // 14: ratelimiter.RateLimiter.GetPolicies:output_type -> ratelimiter.PoliciesResponse
	11, // 15: ratelimiter.RateLimiter.AddPolicy:output_type -> ratelimiter.PolicyResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_rate_limiter_proto_init() }
func file_rate_limiter_proto_init() {
	if File_rate_limiter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rate_limiter_proto_rawDesc), len(file_rate_limiter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rate_limiter_proto_goTypes,
		DependencyIndexes: file_rate_limiter_proto_depIdxs,
		MessageInfos:      file_rate_limiter_proto_msgTypes,
	}.Build()
	File_rate_limiter_proto = out.File
	file_rate_limiter_proto_goTypes = nil
	file_rate_limiter_proto_depIdxs = nil
}
